version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3333:3333"
    environment:                  
      - PORT=3333
      - MONGO_URI=mongodb://mongodb:27017/prontuario
      - JWT_SECRET=albertEistein
    depends_on:
    -  mongodb
    
    #     condition: service_healthy
     

  mongodb:
    image: mongo:latest 
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    #hostname: mongodb
    #healthcheck:
    #  test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5

volumes:
 mongodb_data_container: